name: appium_e2e

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 6 * * 1"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            native-app/node_modules
            backend/node_modules
          key: ${{ runner.os }}-dependencies-${{ hashFiles('native-app/yarn.lock') }}-${{ hashFiles('backend/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-dependencies

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version-file: native-app/.nvmrc
          corepack: true

      - name: Install dependencies
        run: |
          cd native-app
          yarn --frozen-lockfile --prefer-offline
          yarn start &
          sleep 5

      - name: Start API server in background
        run: |
          cd backend
          yarn --frozen-lockfile --prefer-offline
          yarn start &
          sleep 5

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"
          cache: "gradle"

      - name: Install Appium
        run: |
          npm install -g appium
          appium --version

      - name: Start Appium server
        run: appium &

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 31
          target: default
          arch: x86_64
          profile: Pixel_3a_API_31_x86_64

      - name: Start Android emulator
        run: |
          $ANDROID_HOME/emulator/emulator -avd Pixel_3a_API_31_x86_64 -no-skin -no-audio -no-window &
          adb wait-for-device

      - name: Run Appium tests
        run: node native-app/e2e/appium.test.js
